In [1]:
import os
print(os.getcwd())

/Users/kura/pysrc


In [2]:
os.mkdir('data')

FileExistsError: [Errno 17] File exists: 'data'

In [3]:
os.listdir()

['chapter08.ipynb',
 '.DS_Store',
 'Untitled.ipynb',
 'chapter05.ipynb',
 'kadai_chapter07.ipynb',
 'chapter07.ipynb',
 'kadai_chapter05.ipynb',
 'chapter03.ipynb',
 'kadai_chapter03.ipynb',
 'kadai_chapter04.ipynb',
 '.ipynb_checkpoints',
 'chapter06.ipynb',
 'kadai_chapter06.ipynb',
 'chapter04.ipynb',
 'data',
 'kadai_chapter02.ipynb',
 'lecture_voice1.mp3',
 'chapter02.ipynb',
 'lecture_voice2.mp3']

In [4]:
os.path.exists('data')

True

In [5]:
import numpy as np

raw_data = np.loadtxt(
  fname='data//t1.csv', # 相対パス設定
  delimiter=',', # 区切り文字
  encoding ='utf-8') # 文字コード
print('読み込み完了') # 左の記述は省略可能
print('raw_dataの中身') # 省略可能
print(raw_data)

読み込み完了
raw_dataの中身
[[88. 18. 59.]
 [48. 81.  2.]
 [91. 39. 30.]
 [26. 33. 28.]
 [95. 61. 82.]
 [32. 61. 27.]
 [74. 13. 73.]
 [56. 30. 91.]
 [35. 58. 95.]
 [79. 63.  8.]
 [ 9. 52. 76.]
 [98. 51. 29.]
 [ 3. 54. 11.]
 [23. 56. 95.]
 [73. 87. 42.]
 [18. 83. 46.]
 [56. 12. 97.]
 [46. 71. 59.]
 [72. 90. 96.]
 [61. 29. 76.]]


In [6]:
print(type(raw_data))
print(raw_data[0,0])
print(type(raw_data[0,0]))

<class 'numpy.ndarray'>
88.0
<class 'numpy.float64'>


In [7]:
raw_data = np.array([[1,2],[3,4]])
np.savetxt(
    fname='data//write_d.csv', # 出力用のファイルパス
    X=raw_data, # 出力するファイル
    fmt='%0d', # 有効桁数の指定
    delimiter=',') 

In [8]:
raw_data = np.loadtxt(
    fname='data//t2.csv', # ファイルパスの設定
    dtype='int', # 読み込む際に整数型を指定
    delimiter=',', # 区切り文字
    encoding ='utf-8') # 文字コードの指定
print(raw_data)

ValueError: invalid literal for int() with base 10: 'あ'

In [9]:
raw_data = np.loadtxt(
    fname='data//t2.csv',
    dtype='str', # 文字列型に変更
    delimiter=',',
    encoding ='utf-8')
print(raw_data)

[['あ' '18' '59']
 ['48' '81' '2']
 ['91' '39' '30']
 ['26' '33' '28']
 ['95' '61' '82']
 ['32' '61' '27']
 ['74' '13' '73']
 ['56' '30' '91']
 ['35' '58' '95']
 ['79' '63' '8']
 ['9' '52' '76']
 ['98' '51' '29']
 ['3' '54' '11']
 ['23' '56' '95']
 ['73' '87' '42']
 ['18' '83' '46']
 ['56' '12' '97']
 ['46' '71' '59']
 ['72' '90' '96']
 ['61' '29' '76']]


In [10]:
raw_data = np.loadtxt(
    fname='data//t4.csv', # ファイルパス
    delimiter=',', # 区切り文字
    dtype='str', # 文字列を指定
    encoding ='utf-8') # あえて文字コードをのutf-8に指定
print(raw_data)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 0: invalid start byte

In [11]:
raw_data = np.loadtxt(
    fname='data//t4.csv',
    delimiter=',', # 区切り文字
    dtype='str', # 文字列を指定
    # 文字コードを'shift_jis'に指定
    encoding ='shift_jis') 
print(raw_data)

[['あ' '18' '59']
 ['48' '81' '2']
 ['91' '39' '30']
 ['26' '33' '28']
 ['95' '61' '82']
 ['32' '61' '27']
 ['74' '13' '73']
 ['56' '30' '91']
 ['35' '58' '95']
 ['79' '63' '8']
 ['9' '52' '76']
 ['98' '51' '29']
 ['3' '54' '11']
 ['23' '56' '95']
 ['73' '87' '42']
 ['18' '83' '46']
 ['56' '12' '97']
 ['46' '71' '59']
 ['72' '90' '96']
 ['61' '29' '76']]


In [12]:
raw_data = np.loadtxt(
    fname='data//t5.csv', # 欠損のあるファイルを読み込む
    delimiter=',', 
    encoding ='utf-8') # UTF-8のまま

ValueError: Wrong number of columns at line 2