In [1]:
import numpy as np
# 1行ずつ記入し二次元配列を生成
d = np.array([[10,11,12,13,14],
              [15,16,17,18,19],
             [20,21,22,23,24]]) 
print(d) # 配列の中身を全て出力
print(d[1,2]) # 一部を出力(17)
d[1,2] = 100 # 値を変更
print(d) # 配列の中身を全て出力

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
17
[[ 10  11  12  13  14]
 [ 15  16 100  18  19]
 [ 20  21  22  23  24]]


In [2]:
d = np.array([[10,11,12,13,14],
              [15,16,17,18,19],
             [20,21,22,23,24]]) 
print(d[0,2])

12


In [3]:
print(d[1, :])

[15 16 17 18 19]


In [4]:
print(d[:,3])

[13 18 23]


In [5]:
print(d[0:3, 1:4])

[[11 12 13]
 [16 17 18]
 [21 22 23]]


In [6]:
d[0,2] = 112
print(d[0,2])

112


In [7]:
d[:,3] = 77
print(d[:,3])

[77 77 77]


In [8]:
d[0:3,1:4] = 0
print(d[0:3, 1:4])

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[10  0  0  0 14]
 [15  0  0  0 19]
 [20  0  0  0 24]]


In [9]:
import numpy as np
d = np.array([[10,11,12,13],
              [15,16,17,18],
             [20,21,22,23]]) 
d = d - d # 行番号と列番号が同じ要素の加算
print(d) # 全ての要素が 0 
d = d + 1 # 全ての要素に1を加算
print(d) # 全ての要素が 1

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
d = np.array([[10,11,12,13],
              [15,16,17,18],
             [20,21,22,23]]) 
d[1,:] = d[1,:] + d[1,:]
print(d)

[[10 11 12 13]
 [30 32 34 36]
 [20 21 22 23]]


In [11]:
import numpy as np 
d1 = np.arange(1, 91) # 整数値1から90の要素の一次元配列
print(d1)  
print('一次元配列を6行15列の二次元配列に変換')
d2 = d1.reshape(6,15) # reshape(行数,列数)
print(d2) # 二次元配列の出力

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
一次元配列を6行15列の二次元配列に変換
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70 71 72 73 74 75]
 [76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]]


In [12]:
print(np.max(d1)) # 最大値を求める
print(np.min(d1)) # 最小値を求める

90
1


In [13]:
print(np.max(d2,axis=(0))) # 列ごとの最大値
print(np.max(d2,axis=(1))) # 行ごとの最大値
print(np.max(d2)) # 全ての要素の最大値

[76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]
[15 30 45 60 75 90]
90


In [14]:
print(np.sum(d2,axis=(0))) # 列ごとの合計
print(np.sum(d2,axis=(1))) # 行ごとの合計
print(np.sum(d2)) # 全ての要素の合計

[231 237 243 249 255 261 267 273 279 285 291 297 303 309 315]
[ 120  345  570  795 1020 1245]
4095
