In [1]:
# 基礎課題7.1
import numpy as np 
kadai = np.arange(1, 31) # 整数値1から30の要素の一次元配列
kadai = kadai.reshape(5,6) # reshape(行数,列数)
print('表7.1')
print(kadai) # 二次元配列の出力

print('出力例1')
print(kadai[2,2])

print('出力例2')
print(kadai[1:4,1:4])

print('出力例3')
print(kadai[0,:])

print('出力例4')
print(kadai[:,2])

表7.1
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
出力例1
15
出力例2
[[ 8  9 10]
 [14 15 16]
 [20 21 22]]
出力例3
[1 2 3 4 5 6]
出力例4
[ 3  9 15 21 27]


In [2]:
# 基礎課題7. 2
kadai = np.arange(1, 31) # 整数値1から30の要素の一次元配列
kadai = kadai.reshape(5,6) # reshape(行数,列数)

kadai[:, 0] = 0
kadai[:, 5] = 0
kadai[2, :] = 0
print(kadai)


[[ 0  2  3  4  5  0]
 [ 0  8  9 10 11  0]
 [ 0  0  0  0  0  0]
 [ 0 20 21 22 23  0]
 [ 0 26 27 28 29  0]]


In [3]:
# 基礎課題7.3
# step 1
print('step1')
kadai = np.arange(1, 26) 
print(kadai)
print('step2')
kadai = kadai.reshape(5, 5)
print(kadai)

step1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
step2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [4]:
# 基礎課題7.4
print('step1')
kadai = np.zeros(81)
print(kadai)
print('step2')
kadai = kadai.reshape(9,9)
print(kadai)

step1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0.]
step2
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
# 発展課題7.5
data1 = np.array([[1, 2, 3],[4, 5, 6]]) 
# 合計の場合
print('')
print(np.sum(data1,axis=(0))) 
print(np.sum(data1,axis=(1))) 
print(np.sum(data1)) 

# 平均
print('平均')
print(np.mean(data1,axis=(0))) 
print(np.mean(data1,axis=(1))) 
print(np.mean(data1)) 

#  中央値
print('中央値')
print(np.median(data1,axis=(0))) 
print(np.median(data1,axis=(1))) 
print(np.median(data1)) 

# 標準偏差
print('標準偏差')
print(np.std(data1,axis=(0))) 
print(np.std(data1,axis=(1))) 
print(np.std(data1)) 

# 分散
print('分散')
print(np.var(data1,axis=(0))) 
print(np.var(data1,axis=(1))) 
print(np.var(data1)) 

# 最大値
print('最大値')
print(np.max(data1,axis=(0)))
print(np.max(data1,axis=(1)))
print(np.max(data1))

# 最小値 
print('最小値 ')
print(np.min(data1,axis=(0))) 
print(np.min(data1,axis=(1))) 
print(np.min(data1)) 


# 最大値の要素番号
print('大値の要素番号')
print(np.argmax(data1,axis=(0)))
print(np.argmax(data1,axis=(1)))
print(np.argmax(data1))

# 最小値 の要素番号
print('最小値 の要素番号')
print(np.argmin(data1,axis=(0))) 
print(np.argmin(data1,axis=(1))) 
print(np.argmin(data1)) 




[5 7 9]
[ 6 15]
21
平均
[2.5 3.5 4.5]
[2. 5.]
3.5
中央値
[2.5 3.5 4.5]
[2. 5.]
3.5
標準偏差
[1.5 1.5 1.5]
[0.81649658 0.81649658]
1.707825127659933
分散
[2.25 2.25 2.25]
[0.66666667 0.66666667]
2.9166666666666665
最大値
[4 5 6]
[3 6]
6
最小値 
[1 2 3]
[1 4]
1
大値の要素番号
[1 1 1]
[2 2]
5
最小値 の要素番号
[0 0 0]
[0 0]
0


In [6]:
# 発展課題7.6
# ゲーム開始のマルバツゲームの盤面を、2次元配列を用いて表現
d = np.array([['空', '空', '空'], ['空', '空', '空'], ['空', '空', '空']]) 
print(d) # '○' や '×' を入力（置く）前の盤面を出力

# 1 ターン目
d[1,1] = '○' # 盤面の中央に先手プレイヤーの'○'を入力に対応
print(d) # 1回目の先手プレイヤーの行動結果を出力
d[0,0] = '×' # 盤面の左上に後手プレイヤーの'×'を入力に対応
print(d) # 1回目の後手プレイヤーの行動結果を出力

# 2 ターン目
d[0, 2] = '○' # 右上
print(d) # 先手プレイヤーの行動結果を出力
d[2, 0] = '×' # 左下
print(d) # 後手プレイヤーの行動結果を出力 

# 3 ターン目
d[1, 0] = '○' # 中央左
print(d) # 先手プレイヤーの行動結果を出力
d[1, 2] = '×' # 中央右
print(d) # 後手プレイヤーの行動結果を出力

# 4 ターン目
d[0, 1] = '○' # 中央上
print(d) # 先手プレイヤーの行動結果を出力
d[2, 1] = '×' # 中央下
print(d) # 後手プレイヤーの行動結果を出力

# 5 ターン目
d[2, 2] = '○' # 右下
print(d) # 先手プレイヤーの行動結果を出力


[['空' '空' '空']
 ['空' '空' '空']
 ['空' '空' '空']]
[['空' '空' '空']
 ['空' '○' '空']
 ['空' '空' '空']]
[['×' '空' '空']
 ['空' '○' '空']
 ['空' '空' '空']]
[['×' '空' '○']
 ['空' '○' '空']
 ['空' '空' '空']]
[['×' '空' '○']
 ['空' '○' '空']
 ['×' '空' '空']]
[['×' '空' '○']
 ['○' '○' '空']
 ['×' '空' '空']]
[['×' '空' '○']
 ['○' '○' '×']
 ['×' '空' '空']]
[['×' '○' '○']
 ['○' '○' '×']
 ['×' '空' '空']]
[['×' '○' '○']
 ['○' '○' '×']
 ['×' '×' '空']]
[['×' '○' '○']
 ['○' '○' '×']
 ['×' '×' '○']]


In [8]:
d = np.array(
    [['空','空','空','空','空','空','空','空'],
    ['空','空','空','空','空','空','空','空'],
    ['空','空','空','空','空','空','空','空'],
    ['空','空','空','空','空','空','空','空'],
    ['空','空','空','空','空','空','空','空'],
    ['空','空','空','空','空','空','空','空'],
    ['空','空','空','空','空','空','空','空'],
    ['空','空','空','空','空','空','空','空']]
)
print(d)
print('リバーシの初期画面作成')
d[3, 3] = '◯'
d[3, 4] = '●'
d[4, 3] = '●'
d[4, 4] = '◯'
print(d)

print('白の手番')
d[4, 3] = '◯'
d[5, 3] = '◯'
print(d)

print('黒の手番')
d[3, 3] = '●'
d[3, 2] = '●'
print(d)
# 以上のように盤面が全て埋まるまでプログラムを作れば良い。

[['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']]
リバーシの初期画面作成
[['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '◯' '●' '空' '空' '空']
 ['空' '空' '空' '●' '◯' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']]
白の手番
[['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '◯' '●' '空' '空' '空']
 ['空' '空' '空' '◯' '◯' '空' '空' '空']
 ['空' '空' '空' '◯' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']]
黒の手番
[['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '空' '空' '空' '空' '空' '空']
 ['空' '空' '●' '●' '●' '空' '空' 