In [1]:
# 基礎課題 6.1
import numpy as np 
d = np.array([1,3,5,7,13])
# 問１
print(d[[0, 2]])
# 問2
print(d[0:3]) 
print(d[[0, 1, 2]]) # 別解
# 問3
print(d[[1, 2, 4]])
# 問4
print(d[[4]])


[1 5]
[1 3 5]
[1 3 5]
[ 3  5 13]
[13]


In [2]:
# 基礎課題 6.2
tmp = np.zeros(10)
tmp[0:10:2] =  tmp[0:10:2] + 10 
print('step 1:::',tmp)
tmp[0:10:3] =  tmp[0:10:3] - 5 
print('step 2:::',tmp)
tmp[0:10:4] =  tmp[0:10:4] * 5
print('step 3:::',tmp)
tmp[0:10:5] =  tmp[0:10:5] / 10
print('step 4:::',tmp)

########### 別解
tmp = np.zeros(10)
tmp[[0,2,4,6,8]] =  tmp[[0,2,4,6,8]] + 10
print('step 1:::',tmp)
tmp[[0,3,6,9]] =  tmp[[0,3,6,9]] - 5 
print('step 2:::',tmp)
tmp[[0,4,8]] =  tmp[[0,4,8]] * 5
print('step 3:::',tmp)
tmp[[0,5]] =  tmp[[0,5]] / 10
print('step 4:::',tmp)

step 1::: [10.  0. 10.  0. 10.  0. 10.  0. 10.  0.]
step 2::: [ 5.  0. 10. -5. 10.  0.  5.  0. 10. -5.]
step 3::: [25.  0. 10. -5. 50.  0.  5.  0. 50. -5.]
step 4::: [ 2.5  0.  10.  -5.  50.   0.   5.   0.  50.  -5. ]
step 1::: [10.  0. 10.  0. 10.  0. 10.  0. 10.  0.]
step 2::: [ 5.  0. 10. -5. 10.  0.  5.  0. 10. -5.]
step 3::: [25.  0. 10. -5. 50.  0.  5.  0. 50. -5.]
step 4::: [ 2.5  0.  10.  -5.  50.   0.   5.   0.  50.  -5. ]


In [3]:
# 基礎課題 6.3
d = np.arange(6)
print(d[6])

IndexError: index 6 is out of bounds for axis 0 with size 6

# 理由
解答例1: 一次元配列の要素番号6は存在しないため。

解答例2: 一次元配列のサイズを超えたため。

解答例3: 一次元配列d の要素数は6であるが、要素番号は0から始まるため、0, 1, 2, 3, 4, 5の6種類である。そのため、d[6]で指定した要素番号6は存在しない。よってエラー「IndexError: index 6 is out of bounds for axis 0 with size 6」が発生する

In [4]:
# 基礎課題 6.4
d = np.array([1, 2, 3])
goukei = d[0] + d[1] + d[2]
heikin = goukei / 3
print('合計は',goukei,'です。')
print('平均は',heikin,'です。')

合計は 6 です。
平均は 2.0 です。


In [5]:
# 発展課題 6.5
d = np.array([10,11,12,13,14])
print('交換前:',d)
# 10 と14を入れ替える
tmp = d[0]
print('交換1回目:',d)
d[0] = d[2]
print('交換2回目:',d)
d[2] = d[1]
print('交換3回目:',d)
d[1] = d[3]
print('交換4回目:',d)
d[3] = d[4]
print('交換5回目:',d)
d[4] = tmp
print('交換終了:',d)

交換前: [10 11 12 13 14]
交換1回目: [10 11 12 13 14]
交換2回目: [12 11 12 13 14]
交換3回目: [12 11 11 13 14]
交換4回目: [12 13 11 13 14]
交換5回目: [12 13 11 14 14]
交換終了: [12 13 11 14 10]


In [6]:
#別解
d = np.array([10,11,12,13,14])
print('交換前:',d)
# 10 と14を入れ替える
tmp = d[0]
d[0] = d[4]
d[4] = tmp
print(d)
tmp = d[3]
d[3] = d[0]
d[0] = tmp
print(d)
tmp = d[2]
d[2] = d[1]
d[1] = tmp
print(d)
tmp = d[1]
d[1] = d[0]
d[0] = tmp
print('交換終了:',d)

交換前: [10 11 12 13 14]
[14 11 12 13 10]
[13 11 12 14 10]
[13 12 11 14 10]
交換終了: [12 13 11 14 10]


In [7]:
# 誤答例
d = np.array([10,11,12,13,14])
print('交換前:',d)
d[0] = 12
d[1] = 13
d[2] = 11
d[3] = 14
d[4] = 10
print('交換終了:',d)
# 最終的な出力は同じでも、交換アルゴリズムを用いてない。

交換前: [10 11 12 13 14]
交換終了: [12 13 11 14 10]
