In [1]:
# 基礎課題16.1
import numpy as np
d = np.ones((9, 9))
for i in np.arange(1, 10):
    for j in np.arange(1, 10):
        d[i - 1, j - 1] = i *  j
print(d)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 9. 18. 27. 36. 45. 54. 63. 72. 81.]]


In [2]:
import pandas as pd
import os
import glob
sfs = glob.glob('data//subset//*.csv') # subsetフォルダからcsvファイル名の一覧を取得
print('globの結果:', sfs) # csvのファオル名一覧を出力
for sf in sfs: # ファイル名を変えながらファイル一つ一つを読み込むループ
    print(sf, 'の読み込み準備', end = '・・・') # sfには相対パスを格納済み
    data = pd.read_csv(sf, index_col = 0) # sfのファイルパスを利用してcsvの読み込み
    print('読み込み終了')
    print(sf, 'の成績評価開始', end = '・・・')
    for sid in data.index: # 成績を判定するループ
        data.loc[sid, '合計'] = data.loc[sid, '国語':'社会'].sum() # 合計を計算
        if data.loc[sid, '合計'] >= 300: # 300点以上の場合
            data.loc[sid, '判定'] = '合格'
        else: # それ以外の場合
            data.loc[sid, '判定'] = '不合格'
    print('成績評価終了')
    # os.path.splitはファイルパス分割し、[1]にはファイル名だけ抽出されている
    fname = 'data//subset_h//' + os.path.split(sf)[1] # 保存先フォルダを変更する工夫
    print(fname, 'への書き込み開始', end = '・・・')
    data.to_csv(fname, index = True)
    print('書き込み終了')
print('全体の成績評価終了')

globの結果: ['data//subset/2008y_seiseki_5s_g.csv', 'data//subset/2014y_seiseki_5s_g.csv', 'data//subset/2011y_seiseki_5s_g.csv', 'data//subset/2009y_seiseki_5s_g.csv', 'data//subset/2015y_seiseki_5s_g.csv', 'data//subset/1999y_seiseki_5s_g.csv', 'data//subset/2010y_seiseki_5s_g.csv', 'data//subset/2016y_seiseki_5s_g.csv', 'data//subset/2013y_seiseki_5s_g.csv', 'data//subset/2017y_seiseki_5s_g.csv', 'data//subset/2012y_seiseki_5s_g.csv', 'data//subset/2007y_seiseki_5s_g.csv', 'data//subset/2002y_seiseki_5s_g.csv', 'data//subset/2006y_seiseki_5s_g.csv', 'data//subset/2003y_seiseki_5s_g.csv', 'data//subset/2005y_seiseki_5s_g.csv', 'data//subset/2019y_seiseki_5s_g.csv', 'data//subset/2000y_seiseki_5s_g.csv', 'data//subset/2004y_seiseki_5s_g.csv', 'data//subset/2018y_seiseki_5s_g.csv', 'data//subset/2001y_seiseki_5s_g.csv']
data//subset/2008y_seiseki_5s_g.csv の読み込み準備・・・読み込み終了
data//subset/2008y_seiseki_5s_g.csv の成績評価開始・・・成績評価終了
data//subset_h//2008y_seiseki_5s_g.csv への書き込み開始・・・書き込み終了
data//su