# 基礎課題8.1

## 問1
- 正答例
    - Windowsを想定する場合は「c://pysrc//data//t1.csv」
    - Mac を想定する場合は「 /Users/kura/pysrc/data/t1.csv」
    - ただし、図8.8を問題で指定しているため、厳密に正解は「c://pysrc//data//t1.csv」
- 誤答例
    - c://pysrc のように途中までしか書かれていない場合
    - np.loadtxt(fname = 'data//t1.csv')のような命令を記述する場合。

## 問2
- 絶対パスは、cドライブのようなルートからファイルまでのパスを全て記述する必要がある。
- 相対パスは、設定されたカレントディレクトリからファイルまでのパスを記述すれば良い。
- 絶対パスと相対パスは、設定されたカレントディレクトリがcドライブ（ルート）であれば、同一である。一方で、相対パスは、カレントディレクトリからの相対的な位置を記述すれば良いため、絶対パスよりもファイルパスを省略して書くことができる。

## 問3
- 絶対パスを記述したプログラムは、他人のパソコンで実行する場合には、絶対パスを他人のパソコン上のパスに修正しなければならない。しかし、pysrcのようなフォルダをカレントディレクトリとして設定すれば、そのフォルダからの相対的な位置である相対パスを記述したプログラムであれば、他人のパソコンや、自身のパソコンの別の階層からでも、プログラムを修正せずに、作成したプログラムを実行することができる。


In [1]:
# 基礎課題8.2 
# step1 0 から19 までの整数値を持つ2 次元配列を生成
import numpy as np
data1 = np.arange(0, 20).reshape(4, 5)
print(data1)

# step1の続き：data1をCSV形式のdata1.csvとして出力
np.savetxt(
    fname='data//data1.csv', # 出力用のファイルパス
    X=data1, # 出力するファイル
    fmt='%0d', # 有効桁数の指定
    delimiter=',') 
# 注意：カンマ「,」の記述忘れが目立つため注意
# SyntaxError: invalid synta X=data1, # 出力するファイル などが出る場合などはカンマ「,」の記述忘れ

# このセルを実行すれば、dataフォルダに、変数data1と同じ数値を、小数点なしで、カンマ「,」で区切って、data1.csvというファイル名で出力する
# 上記のような設定で、pysrc フォルダのdataフォルダに data1.csv が保存される

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [7]:
# step 2  20 から39 までの整数値を持つ2 次元配列を生成
data2 = np.arange(20, 40).reshape(4, 5)
print(data2)
# step 2の続き  data2をCSV形式のdata2.csvとして出力
np.savetxt(
    fname='data//data2.csv', # 出力用のファイルパス
    X=data2, # 出力するファイル
    fmt='%0d', # 有効桁数の指定
    delimiter=',') 
# このセルを実行すれば、dataフォルダに、変数data2と同じ数値を、小数点なしで、カンマ「,」で区切って、data2.csvというファイル名で出力する
# 上記のような設定で、pysrc フォルダのdataフォルダに data2.csv が保存される

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [8]:
# step 3 step1で作成したdata1.csvのファイルを読み込み、それを変数data1に代入
data1 = np.loadtxt(
    fname='data//data1.csv', # ファイルパスの設定
    dtype='int', # 読み込む際に整数型を指定
    delimiter=',', # 区切り文字
    encoding ='utf-8') # 文字コードの指定
# コンピュータ上のpysrcフォルダにある、dataフォルダ内のdata1.csv を読み込み、その数値（二次元配列）を変数data1として扱う
# この時点でファイルを書き込み、そのファイルを読み込む操作ができるようになっている

# step 4 step2で作成したdata2.csvのファイルを読み込み、それを変数data2に代入
data2 = np.loadtxt(
    fname='data//data2.csv', # ファイルパスの設定
    dtype='int', # 読み込む際に整数型を指定
    delimiter=',', # 区切り文字
    encoding ='utf-8') # 文字コードの指定
# コンピュータ上のpysrcフォルダにある、dataフォルダ内のdata2.csv を読み込み、その数値（二次元配列）を変数data2として扱う

In [9]:
# step 5 読み込んだdata1とdata2のそれぞれの要素を足し合わせて、変数data3とする。
data3 = data1 + data2
print(data3)
# step 6 data3の数値をstep 2 や step 3 と同様な方法で、CSV形式のファイルとして出力する。
np.savetxt(
    fname='data//data3.csv', # 出力用のファイルパス
    X=data3, # 出力するファイル
    fmt='%0d', # 有効桁数の指定
    delimiter=',') 
# このセルを実行すれば、dataフォルダに、変数data3と同じ数値を、小数点なしで、カンマ「,」で区切って、data3.csvというファイル名で出力する
# 上記のような設定で、pysrc フォルダのdataフォルダに data3.csv が保存される


[[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]


# 基礎課題8.3

- 問1: ファイル読み込み時にint型を指定したが、そのファイルには日本語の「あ」が含まれていたため、エラーが発生した。つまり、指定した型とは異なる文字列がファイルに含まれていることが問題である。
- 問2: 「ファイルの先頭でUTF-8では翻訳できない0x82から始まるコードがあります」とエラーが出ている。読み込むファイルがUTF-8ではない別の文字コードで保存されていることが原因


In [12]:
# 基礎課題8.4

# プログラム作成前に、メモ帳などで csv ファイルを作成する
# 1, 2,
# 3, 4 
# のように入力する
# エラー not found が発生する場合は、保存したファイルu8_uft8.csvや、u8_sj.csvが
# pysrc フォルダの data フォルダにあるかを確認

#  作成したファイルを読み込む
tmp1 = np.loadtxt(
    fname='data//u8_uft8.csv', # ファイルパスの設定
    dtype='int', # 読み込む際に整数型を指定
    delimiter=',', # 区切り文字
    encoding ='utf-8') # 文字コードの指定
print(tmp1)
tmp2 = np.loadtxt(
    fname='data//u8_sj.csv', # ファイルパスの設定
    dtype='int', # 読み込む際に整数型を指定
    delimiter=',', # 区切り文字
    encoding ='shift-jis') # 文字コードの指定
print(tmp2)
# 作成したファイルは、整数値であるため、 dtype='int' を忘れないようにすること。

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [11]:
# 発展課題8.5の問題
import os, numpy as np # import の省略形
# 既にダウンロード済みのsubdirフォルダ内のファイル、またはフォルダの一覧を取得
filepass = os.listdir('data//subdir')
print('subdirフォルダには', filepass, 'が含まれています。')
# 1次元配列のようにfilepass[x]の要素番号 x を指定して、一つのファイル名を取得
print('読み込むfilepass[0]は', filepass[0], 'です。')
# filepass[0]のファイル名を利用したファイルパスのデータを読み込む
data0 = np.loadtxt(fname = 'data//subdir//' + filepass[0], delimiter = ',', encoding = 'utf-8')
print(data0) 

print('読み込むfilepass[1]は', filepass[1], 'です。') # 別のファイル名を指定


# この課題では　'data//subdir//' 　を　'data//subdir'と記述するミスがみられます。
# エラーメッセージが「OSError: data//subdirsub_data1.csv not found.」の場合は注意しましょう。

# NotADirectoryError：WinError 267 ディレクトリ名が無効です。：data//subdir.zip
# .zip は 圧縮されたファイルを示す拡張子です。ファイルを読み込む際には、圧縮されていない .csv 形式のデータを読み込む必要があります。
# また、os.listdir 関数は、フォルダを指定することを想定しているため、具体的なファイル名を記述せずにos.listdir('data//subdir')のようにフォルダまで記述します。

subdirフォルダには ['sub_data1.csv', 'sub_data2.csv'] が含まれています。
読み込むfilepass[0]は sub_data1.csv です。
[[48. 81.  2.]
 [91. 39. 30.]
 [26. 33. 28.]]
読み込むfilepass[1]は sub_data2.csv です。


In [4]:
# 発展課題8.5の解答例
import os, numpy as np # import の省略形
# 既にダウンロード済みのsubdirフォルダ内のファイル、またはフォルダの一覧を取得
filepass = os.listdir('data//subdir')
print('subdirフォルダには', filepass, 'が含まれています。')
# 1次元配列のようにfilepass[x]の要素番号 x を指定して、一つのファイル名を取得
print('読み込むfilepass[0]は', filepass[0], 'です。')
# filepass[0]のファイル名を利用したファイルパスのデータを読み込む
data0 = np.loadtxt(fname = 'data//subdir//' + filepass[0], delimiter = ',', encoding = 'utf-8')
print(data0) 

print('読み込むfilepass[1]は', filepass[1], 'です。') # 別のファイル名を指定

data1 = np.loadtxt(fname='data//subdir//' + filepass[1], delimiter=',', encoding ='utf-8')
print(data1)

subdirフォルダには ['sub_data1.csv', 'sub_data2.csv'] が含まれています。
読み込むfilepass[0]は sub_data1.csv です。
[[48. 81.  2.]
 [91. 39. 30.]
 [26. 33. 28.]]
読み込むfilepass[1]は sub_data2.csv です。
[[46. 71. 59.]
 [72. 90. 96.]
 [61. 29. 76.]]


# 絶対パス

- sub_data1.csvの絶対パスは、c://pysrc//data//subdir//sub_data1.csv です。
- sub_data2.csvの絶対パスは、c://pysrc//data//subdir//sub_data2.csv です。
