# プログラム8.1

In [ ]:
import os
print(os.getcwd())

# プログラム8.2

In [ ]:
os.mkdir('data')

# プログラム8.3

In [ ]:
os.listdir()

# プログラム8.4

In [ ]:
os.path.exists('data')

# プログラム8.5

In [2]:
import numpy as np
# csv形式のファイルを2次元配列として変数に代入
raw_data = np.loadtxt(
  fname = 'data//t1.csv', # 相対パスの指定
  delimiter = ',', # 区切り文字の指定
  encoding = 'utf-8') # 文字コードの指定
print('読み込み完了') # 左の記述は省略可能
print('raw_dataの中身') # 省略可能
print(raw_data) # 読み込んだデータを出力

読み込み完了
raw_dataの中身
[[88. 18. 59.]
 [48. 81.  2.]
 [91. 39. 30.]
 [26. 33. 28.]
 [95. 61. 82.]
 [32. 61. 27.]
 [74. 13. 73.]
 [56. 30. 91.]
 [35. 58. 95.]
 [79. 63.  8.]
 [ 9. 52. 76.]
 [98. 51. 29.]
 [ 3. 54. 11.]
 [23. 56. 95.]
 [73. 87. 42.]
 [18. 83. 46.]
 [56. 12. 97.]
 [46. 71. 59.]
 [72. 90. 96.]
 [61. 29. 76.]]


# プログラム8.6

In [ ]:
print(type(raw_data))
print(raw_data[0, 0])
print(type(raw_data[0, 0]))

# プログラム8.7

In [3]:
raw_data = np.loadtxt(
  fname = 'data//t1.csv', # 相対パスの指定
  delimiter = ',', # 区切り文字の指定
  encoding = 'utf-8', # 文字コードの指定
  dtype = 'int') # 整数型で読み込む指定
print(raw_data) # 読み込んだデータを出力

[[88 18 59]
 [48 81  2]
 [91 39 30]
 [26 33 28]
 [95 61 82]
 [32 61 27]
 [74 13 73]
 [56 30 91]
 [35 58 95]
 [79 63  8]
 [ 9 52 76]
 [98 51 29]
 [ 3 54 11]
 [23 56 95]
 [73 87 42]
 [18 83 46]
 [56 12 97]
 [46 71 59]
 [72 90 96]
 [61 29 76]]


# プログラム8.8

In [4]:
raw_data = np.array([[1,2],[3,4]])
np.savetxt(
    fname='data//write_d.csv', # 出力用のファイルパス
    X=raw_data, # 出力するファイル
    fmt='%0d', # 有効桁数の指定
    delimiter=',') 

# プログラム8.9
エラーが発生します

In [5]:
raw_data = np.loadtxt(fname = 'data//t2.csv', # ファイルパスの設定
    dtype = 'int', # 読み込む際に整数型を指定
    delimiter = ',', # 区切り文字
    encoding = 'utf-8') # 文字コードの指定
print(raw_data)

ValueError: invalid literal for int() with base 10: 'あ'

# プログラム8.10

In [ ]:
raw_data = np.loadtxt(fname = 'data//t2.csv',
    dtype = 'str', #  文字列型に変更
    delimiter = ',', encoding = 'utf-8')
print(raw_data)

# プログラム8.11
エラーが発生します

In [ ]:
raw_data = np.loadtxt(fname = 'data//t4.csv', delimiter = ',', dtype = 'str', 
    encoding = 'utf-8') # 文字コードutf-8の指定
print(raw_data)

# プログラム8.12

In [ ]:
raw_data = np.loadtxt(fname = 'data//t4.csv',
    delimiter = ',', # 区切り文字
    dtype = 'str', # 文字列を指定
    # 文字コードを'shift_jis'に指定
    encoding = 'shift_jis') 
print(raw_data)

# プログラム8.13
エラーが発生します

In [ ]:
raw_data = np.loadtxt(fname = 'data//t5.csv', # 欠損のあるファイルを読み込む
    delimiter = ',', encoding = 'utf-8') # 指定はUTF-8のまま
# 本書の通りにt5.csvを直接修正しましょう。