# プログラム16.1

In [1]:
import numpy as np
# np.arange(1, 10)の中身は[1, 2, 3, 4, 5, 6, 7, 8, 9]
for kazu in np.arange(1, 10): # 一の段の計算
    print('一の段の1 ×', kazu, '=', 1 * kazu, 'です') 
for kazu in np.arange(1, 10): # 二の段の計算
    print('二の段の2 ×', kazu, '=', 2 * kazu, 'です') 
for kazu in np.arange(1, 10): # 三の段の計算
    print('三の段の3 ×', kazu, '=', 3 * kazu, 'です') 
for kazu in np.arange(1, 10): # 四の段の計算
    print('四の段の4 ×', kazu, '=', 4 * kazu, 'です') 
for kazu in np.arange(1, 10): # 五の段の計算
    print('五の段の5 ×', kazu, '=', 5 * kazu, 'です') 
for kazu in np.arange(1, 10): # 六の段の計算
    print('六の段の6 ×', kazu, '=', 6 * kazu, 'です') 
for kazu in np.arange(1, 10): # 七の段の計算
    print('七の段の7 ×', kazu, '=', 7 * kazu, 'です') 
for kazu in np.arange(1, 10): # 八の段の計算
    print('八の段の8 ×', kazu, '=', 8 * kazu, 'です') 
for kazu in np.arange(1, 10): # 九の段の計算
    print('九の段の9 ×', kazu, '=', 9 * kazu, 'です') 

一の段の1 × 1 = 1 です
一の段の1 × 2 = 2 です
一の段の1 × 3 = 3 です
一の段の1 × 4 = 4 です
一の段の1 × 5 = 5 です
一の段の1 × 6 = 6 です
一の段の1 × 7 = 7 です
一の段の1 × 8 = 8 です
一の段の1 × 9 = 9 です
二の段の2 × 1 = 2 です
二の段の2 × 2 = 4 です
二の段の2 × 3 = 6 です
二の段の2 × 4 = 8 です
二の段の2 × 5 = 10 です
二の段の2 × 6 = 12 です
二の段の2 × 7 = 14 です
二の段の2 × 8 = 16 です
二の段の2 × 9 = 18 です
三の段の3 × 1 = 3 です
三の段の3 × 2 = 6 です
三の段の3 × 3 = 9 です
三の段の3 × 4 = 12 です
三の段の3 × 5 = 15 です
三の段の3 × 6 = 18 です
三の段の3 × 7 = 21 です
三の段の3 × 8 = 24 です
三の段の3 × 9 = 27 です
四の段の4 × 1 = 4 です
四の段の4 × 2 = 8 です
四の段の4 × 3 = 12 です
四の段の4 × 4 = 16 です
四の段の4 × 5 = 20 です
四の段の4 × 6 = 24 です
四の段の4 × 7 = 28 です
四の段の4 × 8 = 32 です
四の段の4 × 9 = 36 です
五の段の5 × 1 = 5 です
五の段の5 × 2 = 10 です
五の段の5 × 3 = 15 です
五の段の5 × 4 = 20 です
五の段の5 × 5 = 25 です
五の段の5 × 6 = 30 です
五の段の5 × 7 = 35 です
五の段の5 × 8 = 40 です
五の段の5 × 9 = 45 です
六の段の6 × 1 = 6 です
六の段の6 × 2 = 12 です
六の段の6 × 3 = 18 です
六の段の6 × 4 = 24 です
六の段の6 × 5 = 30 です
六の段の6 × 6 = 36 です
六の段の6 × 7 = 42 です
六の段の6 × 8 = 48 です
六の段の6 × 9 = 54 です
七の段の7 × 1 = 7 です
七の段の7 × 2 = 14 です
七の段の7 × 3 = 2

# プログラム16.2

In [2]:
import numpy as np
# 計算結果の出力に漢数字を使うために kanzi_dan を作成
# 繰り返し処理を簡単にするため、配列の要素番号0に'零'を用意
kanzi_dan = np.array(['零', '一', '二', '三', '四', '五', '六', '七', '八', '九'])

for dan in np.arange(1, 10): # 〇〇の段を設定するためのループ
    print(kanzi_dan[dan], 'の段の計算開始') # kanzi_dan[dan]は'一'から'九'に置き換わる
    
    for kazu in np.arange(1, 10): # 1×〇〇から9×〇〇の〇〇を置き換えるために利用
        print(kanzi_dan[dan], 'の段の', dan, '×', kazu, '=', dan *  kazu, 'です')
    print(kanzi_dan[dan], 'の段の計算終了')
    
print('九九の計算終了')

一 の段の計算開始
一 の段の 1 × 1 = 1 です
一 の段の 1 × 2 = 2 です
一 の段の 1 × 3 = 3 です
一 の段の 1 × 4 = 4 です
一 の段の 1 × 5 = 5 です
一 の段の 1 × 6 = 6 です
一 の段の 1 × 7 = 7 です
一 の段の 1 × 8 = 8 です
一 の段の 1 × 9 = 9 です
一 の段の計算終了
二 の段の計算開始
二 の段の 2 × 1 = 2 です
二 の段の 2 × 2 = 4 です
二 の段の 2 × 3 = 6 です
二 の段の 2 × 4 = 8 です
二 の段の 2 × 5 = 10 です
二 の段の 2 × 6 = 12 です
二 の段の 2 × 7 = 14 です
二 の段の 2 × 8 = 16 です
二 の段の 2 × 9 = 18 です
二 の段の計算終了
三 の段の計算開始
三 の段の 3 × 1 = 3 です
三 の段の 3 × 2 = 6 です
三 の段の 3 × 3 = 9 です
三 の段の 3 × 4 = 12 です
三 の段の 3 × 5 = 15 です
三 の段の 3 × 6 = 18 です
三 の段の 3 × 7 = 21 です
三 の段の 3 × 8 = 24 です
三 の段の 3 × 9 = 27 です
三 の段の計算終了
四 の段の計算開始
四 の段の 4 × 1 = 4 です
四 の段の 4 × 2 = 8 です
四 の段の 4 × 3 = 12 です
四 の段の 4 × 4 = 16 です
四 の段の 4 × 5 = 20 です
四 の段の 4 × 6 = 24 です
四 の段の 4 × 7 = 28 です
四 の段の 4 × 8 = 32 です
四 の段の 4 × 9 = 36 です
四 の段の計算終了
五 の段の計算開始
五 の段の 5 × 1 = 5 です
五 の段の 5 × 2 = 10 です
五 の段の 5 × 3 = 15 です
五 の段の 5 × 4 = 20 です
五 の段の 5 × 5 = 25 です
五 の段の 5 × 6 = 30 です
五 の段の 5 × 7 = 35 です
五 の段の 5 × 8 = 40 です
五 の段の 5 × 9 = 45 です
五 の段の計算終了
六 の段の計算開始
六 の段の 6 ×

# プログラム16.2の簡略版

In [1]:
import numpy as np
for dan in np.arange(1, 10):
    print(dan,'の段の計算開始')
    for kazu in np.arange(1, 10):
        print(dan, 'の段の', dan, '×', kazu, '=', dan *  kazu, 'です')
    print(dan,'の段の計算終了')
print('九九の計算終了')    

1 の段の計算開始
1 の段の 1 × 1 = 1 です
1 の段の 1 × 2 = 2 です
1 の段の 1 × 3 = 3 です
1 の段の 1 × 4 = 4 です
1 の段の 1 × 5 = 5 です
1 の段の 1 × 6 = 6 です
1 の段の 1 × 7 = 7 です
1 の段の 1 × 8 = 8 です
1 の段の 1 × 9 = 9 です
1 の段の計算終了
2 の段の計算開始
2 の段の 2 × 1 = 2 です
2 の段の 2 × 2 = 4 です
2 の段の 2 × 3 = 6 です
2 の段の 2 × 4 = 8 です
2 の段の 2 × 5 = 10 です
2 の段の 2 × 6 = 12 です
2 の段の 2 × 7 = 14 です
2 の段の 2 × 8 = 16 です
2 の段の 2 × 9 = 18 です
2 の段の計算終了
3 の段の計算開始
3 の段の 3 × 1 = 3 です
3 の段の 3 × 2 = 6 です
3 の段の 3 × 3 = 9 です
3 の段の 3 × 4 = 12 です
3 の段の 3 × 5 = 15 です
3 の段の 3 × 6 = 18 です
3 の段の 3 × 7 = 21 です
3 の段の 3 × 8 = 24 です
3 の段の 3 × 9 = 27 です
3 の段の計算終了
4 の段の計算開始
4 の段の 4 × 1 = 4 です
4 の段の 4 × 2 = 8 です
4 の段の 4 × 3 = 12 です
4 の段の 4 × 4 = 16 です
4 の段の 4 × 5 = 20 です
4 の段の 4 × 6 = 24 です
4 の段の 4 × 7 = 28 です
4 の段の 4 × 8 = 32 です
4 の段の 4 × 9 = 36 です
4 の段の計算終了
5 の段の計算開始
5 の段の 5 × 1 = 5 です
5 の段の 5 × 2 = 10 です
5 の段の 5 × 3 = 15 です
5 の段の 5 × 4 = 20 です
5 の段の 5 × 5 = 25 です
5 の段の 5 × 6 = 30 です
5 の段の 5 × 7 = 35 です
5 の段の 5 × 8 = 40 です
5 の段の 5 × 9 = 45 です
5 の段の計算終了
6 の段の計算開始
6 の段の 6 ×

# プログラム16.2の別の書き方

In [3]:
# パターン2 漢数字をアラビア数字に変換するライブラリ
import numpy as np
import unicodedata
kansuuzi = ['一', '二', '三', '四', '五', '六', '七', '八', '九']
for dan in kansuuzi:
    print(dan,'の段の計算開始')
    for kazu in np.arange(1, 10):
        suuzi_dan = unicodedata.numeric(dan) # 漢数字にアラビア数字に変換
        print(dan, 'の段の', suuzi_dan, '×', kazu, '=', suuzi_dan *  kazu, 'です')
    print(dan,'の段の計算終了')
print('九九の計算終了')

一 の段の計算開始
一 の段の 1.0 × 1 = 1.0 です
一 の段の 1.0 × 2 = 2.0 です
一 の段の 1.0 × 3 = 3.0 です
一 の段の 1.0 × 4 = 4.0 です
一 の段の 1.0 × 5 = 5.0 です
一 の段の 1.0 × 6 = 6.0 です
一 の段の 1.0 × 7 = 7.0 です
一 の段の 1.0 × 8 = 8.0 です
一 の段の 1.0 × 9 = 9.0 です
一 の段の計算終了
二 の段の計算開始
二 の段の 2.0 × 1 = 2.0 です
二 の段の 2.0 × 2 = 4.0 です
二 の段の 2.0 × 3 = 6.0 です
二 の段の 2.0 × 4 = 8.0 です
二 の段の 2.0 × 5 = 10.0 です
二 の段の 2.0 × 6 = 12.0 です
二 の段の 2.0 × 7 = 14.0 です
二 の段の 2.0 × 8 = 16.0 です
二 の段の 2.0 × 9 = 18.0 です
二 の段の計算終了
三 の段の計算開始
三 の段の 3.0 × 1 = 3.0 です
三 の段の 3.0 × 2 = 6.0 です
三 の段の 3.0 × 3 = 9.0 です
三 の段の 3.0 × 4 = 12.0 です
三 の段の 3.0 × 5 = 15.0 です
三 の段の 3.0 × 6 = 18.0 です
三 の段の 3.0 × 7 = 21.0 です
三 の段の 3.0 × 8 = 24.0 です
三 の段の 3.0 × 9 = 27.0 です
三 の段の計算終了
四 の段の計算開始
四 の段の 4.0 × 1 = 4.0 です
四 の段の 4.0 × 2 = 8.0 です
四 の段の 4.0 × 3 = 12.0 です
四 の段の 4.0 × 4 = 16.0 です
四 の段の 4.0 × 5 = 20.0 です
四 の段の 4.0 × 6 = 24.0 です
四 の段の 4.0 × 7 = 28.0 です
四 の段の 4.0 × 8 = 32.0 です
四 の段の 4.0 × 9 = 36.0 です
四 の段の計算終了
五 の段の計算開始
五 の段の 5.0 × 1 = 5.0 です
五 の段の 5.0 × 2 = 10.0 です
五 の段の 5.0 × 3 = 1

# プログラム16.2の別の書き方

In [5]:
# 別の書き方
import numpy as np
import unicodedata

kansuuzi = ['一', '二', '三', '四', '五', '六', '七', '八', '九']
for dan in kansuuzi:
    print(dan,'の段の計算開始')
    for kazu in np.arange(1, 10):
        suuzi_dan = unicodedata.numeric(dan)
        print(dan, 'の段の', suuzi_dan, '×', kazu, '=', suuzi_dan *  kazu, 'です')
    print(dan,'の段の計算終了')
print('九九の計算終了')

一 の段の計算開始
一 の段の 1.0 × 1 = 1.0 です
一 の段の 1.0 × 2 = 2.0 です
一 の段の 1.0 × 3 = 3.0 です
一 の段の 1.0 × 4 = 4.0 です
一 の段の 1.0 × 5 = 5.0 です
一 の段の 1.0 × 6 = 6.0 です
一 の段の 1.0 × 7 = 7.0 です
一 の段の 1.0 × 8 = 8.0 です
一 の段の 1.0 × 9 = 9.0 です
一 の段の計算終了
二 の段の計算開始
二 の段の 2.0 × 1 = 2.0 です
二 の段の 2.0 × 2 = 4.0 です
二 の段の 2.0 × 3 = 6.0 です
二 の段の 2.0 × 4 = 8.0 です
二 の段の 2.0 × 5 = 10.0 です
二 の段の 2.0 × 6 = 12.0 です
二 の段の 2.0 × 7 = 14.0 です
二 の段の 2.0 × 8 = 16.0 です
二 の段の 2.0 × 9 = 18.0 です
二 の段の計算終了
三 の段の計算開始
三 の段の 3.0 × 1 = 3.0 です
三 の段の 3.0 × 2 = 6.0 です
三 の段の 3.0 × 3 = 9.0 です
三 の段の 3.0 × 4 = 12.0 です
三 の段の 3.0 × 5 = 15.0 です
三 の段の 3.0 × 6 = 18.0 です
三 の段の 3.0 × 7 = 21.0 です
三 の段の 3.0 × 8 = 24.0 です
三 の段の 3.0 × 9 = 27.0 です
三 の段の計算終了
四 の段の計算開始
四 の段の 4.0 × 1 = 4.0 です
四 の段の 4.0 × 2 = 8.0 です
四 の段の 4.0 × 3 = 12.0 です
四 の段の 4.0 × 4 = 16.0 です
四 の段の 4.0 × 5 = 20.0 です
四 の段の 4.0 × 6 = 24.0 です
四 の段の 4.0 × 7 = 28.0 です
四 の段の 4.0 × 8 = 32.0 です
四 の段の 4.0 × 9 = 36.0 です
四 の段の計算終了
五 の段の計算開始
五 の段の 5.0 × 1 = 5.0 です
五 の段の 5.0 × 2 = 10.0 です
五 の段の 5.0 × 3 = 1

# プログラム16.3

In [2]:
d = np.array([[33, 44, 55, 66], 
              [199, 231, 333, 751]])
for i in np.arange(2): # iは行の移動に利用   
      for j in np.arange(4): # jは列の移動に利用    
            print('行(i)=', i, '列(j)=', j,
            'の要素は', d[i, j])

行(i)= 0 列(j)= 0 の要素は 33
行(i)= 0 列(j)= 1 の要素は 44
行(i)= 0 列(j)= 2 の要素は 55
行(i)= 0 列(j)= 3 の要素は 66
行(i)= 1 列(j)= 0 の要素は 199
行(i)= 1 列(j)= 1 の要素は 231
行(i)= 1 列(j)= 2 の要素は 333
行(i)= 1 列(j)= 3 の要素は 751


# プログラム16.4

In [4]:
for i in np.arange(d.shape[0]): # d.shape[0]は行数
    for j in np.arange(d.shape[1]): # d.shape[1]は列数  
        print('行(i)=', i, '列(j)=', j, 'の要素は', d[i, j])

行(i)= 0 列(j)= 0 の要素は 33
行(i)= 0 列(j)= 1 の要素は 44
行(i)= 0 列(j)= 2 の要素は 55
行(i)= 0 列(j)= 3 の要素は 66
行(i)= 1 列(j)= 0 の要素は 199
行(i)= 1 列(j)= 1 の要素は 231
行(i)= 1 列(j)= 2 の要素は 333
行(i)= 1 列(j)= 3 の要素は 751


# プログラム16.5

In [5]:
# 9 行 9 列の要素1の2次元配列を生成
d = np.ones((9, 9), dtype = 'int') 
# i を i 段としても利用
for i in np.arange(d.shape[0]): 
  # i 段にかける数値 j としても利用
  for j in np.arange(d.shape[1]):
    d[i, j] = (i + 1) * (j + 1)
print(d)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


# コラム
# プログラム16.8

In [6]:
d = np.array([[1, 2],[3, 4]])
for i in d:
    print(i) 

[1 2]
[3 4]


# プログラム16.9

In [7]:
for i, element in np.ndenumerate(d):
    print(i, element)
    print(d[i[0], i[1]])

(0, 0) 1
1
(0, 1) 2
2
(1, 0) 3
3
(1, 1) 4
4
