# プログラム6.1

In [1]:
import numpy as np 
d = np.array([12, 23, 34])
print(d) # 1次元配列の中身を出力
print(d[2]) # 1次元配列の一部を出力(34)
d[2] = 55 # 代入場所を指定して55と変更
print(d) # 1次元配列の出力

[12 23 34]
34
[12 23 55]


# プログラム6.2

In [2]:
a = np.arange(4) # 0, 1, 2, 3を持つ1次元配列
print('aの要素は', a)
b = np.arange(0, 10, 2) # 0以上10未満の範囲で
print('bの要素は', b) # 2ずつ増加
c = np.ones(8) # 要素1 を8 個持つ1次元配列
print('cの要素は', c)
d = np.zeros(8) # 要素0を8 個持つ1次元配列
print('dの要素は', d)
e = np.linspace(0, 10, 5) # 等間隔に要素を
print('eの要素は', e) # 5 個作成

aの要素は [0 1 2 3]
bの要素は [0 2 4 6 8]
cの要素は [1. 1. 1. 1. 1. 1. 1. 1.]
dの要素は [0. 0. 0. 0. 0. 0. 0. 0.]
eの要素は [ 0.   2.5  5.   7.5 10. ]


# プログラム6.3

In [3]:
d = np.array([12, 23, 34])
print(d[2])
print(d[-1])

34
34


# プログラム6.4

In [4]:
print(d[[1, 2]]) 
print(d[1:3])

[23 34]
[23 34]


# プログラム6.5

In [5]:
print(d[[0, 1]]) 
print(d[0:2])

[12 23]
[12 23]


# プログラム6.6

In [6]:
print(d[[0, 2]])
print(d[0:3:2])

[12 34]
[12 34]


# プログラム6.7

In [7]:
import numpy as np 
d = np.array([12, 25, 36])
d[2] = 58
print(d) 

[12 25 58]


# プログラム6.8

In [8]:
d[0:2] = 7
print(d)

[ 7  7 58]


# プログラム6.9

In [9]:
d[0:3:2] = 9
print(d)

[9 7 9]


# プログラム6.10

In [10]:
import numpy as np 
a = np.array([10, 20, 30])
b = np.array([45, 55, 65])
a = a + a # 1次元配列同士の演算 [10 + 10, 20 + 20, 30 + 30]
print(a)
b = b + a # 1次元配列同士の演算 [45 + 20, 55 + 40, 65 + 60]
print(b)
a = a + 1 # 1次元配列と数値の演算 [20 + 1, 40 + 1, 60 + 1]
print(a)

[20 40 60]
[ 65  95 125]
[21 41 61]


# プログラム6.11

In [11]:
v = np.array([11,22,33])
v[0] = v[0] + 1 # [11 + 1, 22, 33]
print(v) # [12 22 33] を出力
v[0:2] = v[0:2] + 1 # [12 + 1, 22 + 1,33]
print(v) # [13 23 33] を出力
v[0:3:2] = v[0:3:2] + 1 # [13 + 1, 23, 33 + 1]
print(v) # [14 23 34] を出力

[12 22 33]
[13 23 33]
[14 23 34]
